[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
